In [1]:
#pip install numpy


In [2]:
import numpy as np

In [3]:
myList=[1,2,3,4,5]

In [4]:
print(myList)

[1, 2, 3, 4, 5]


In [5]:
type(myList)

list

In [6]:
#dir(np)

In [7]:
#help(np)

In [8]:
arr = np.array(myList)

In [9]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
#shape of the array
arr.shape

(5,)

In [11]:
arr.size

5

In [12]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [13]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [14]:
#Numpy arrayindexing

# Get the first element from the following array:

my_lst1=[1,2,3,4,5]
arr = np.array(my_lst1)

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
print(arr[0])

1


In [17]:
# Get the second element from the following array.
print(arr[1])

2


In [18]:
# Get third and fourth elements from the following array and add them.
print("The third element is:",arr[2],"and fourth element is:",arr[3])



The third element is: 3 and fourth element is: 4


In [19]:
# Access 2D array

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [20]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [21]:
arr[1,2]

4

In [22]:
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [23]:
#Access the element on the 2nd row,5th column:
arr[1,4]

6

In [24]:
valArr = np.array([[1,2,3],[4,5,6]]) #create a 2D array
#print the variable
#get shape
#get size
#index:first row first element
#index:second row third element
print("printing the variable value",valArr)
print("\n")
print("printing the size:",valArr.size,"\n")
print("printing the shape:",valArr.shape,"\n")
print("Indexing 1st row:",valArr[0,0],"\n")
print("Indexing 2nd row:",valArr[1,2],"\n")

printing the variable value [[1 2 3]
 [4 5 6]]


printing the size: 6 

printing the shape: (2, 3) 

Indexing 1st row: 1 

Indexing 2nd row: 6 



In [25]:
# Negative Indexing

valArr= np.array([[1,2,3],[4,5,6]])
print(valArr)

[[1 2 3]
 [4 5 6]]


In [26]:
valArr[1,-2]

5

In [27]:
#Numpy Array Slicing

mylist=[1,2,3,4,5,6,7,8,9,10]

arr = np.array(mylist)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
#arr[start end]
arr[0:5]

array([1, 2, 3, 4, 5])

In [29]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [31]:
arr[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[-3:-1]

array([8, 9])

In [33]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
#step
arr[::2]

array([1, 3, 5, 7, 9])

In [35]:
arr[1::3]

array([2, 5, 8])

In [36]:
arr[1::4]

array([ 2,  6, 10])

In [37]:
#Arange function

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [40]:
#Linspace
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [41]:
# create a 5*5 array
newArr= np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])
print("Print the Variable value : \n " ,newArr, "\n")
print("The shape of Variable :\n" ,newArr.shape, "\n") # Prints "(2,3)"\
print("The shape of variables :\n" ,newArr.size, "\n")
#indexing using both row and column
print('2nd element on 3rd row:',newArr[2,1])
print('1st element on 4th row:',newArr[3,0])

Print the Variable value : 
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [20 25 30 35 40]] 

The shape of Variable :
 (5, 5) 

The shape of variables :
 25 

2nd element on 3rd row: 2
1st element on 4th row: 11


In [42]:
#arr = np.array(1,2,3,4) # Let numpy choose the datatype
arr = np.array([1.0,2.0])

print(arr.dtype)

float64


In [43]:
arr = np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [44]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [45]:
import numpy as np
arr = np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [46]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [47]:
arr = np.array([1,2,3,4,5],dtype=np.int64)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [48]:
arr = np.array([1,2,3,4,5],dtype=np.float64)
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [49]:
arr

array([1., 2., 3., 4., 5.])

In [50]:
#Array math
X=np.array([[1,2],[3,4]],dtype=np.float64)
Y=np.array([[5,6],[7,8]],dtype=np.float64)


In [51]:
X+Y

array([[ 6.,  8.],
       [10., 12.]])

In [52]:
X-Y

array([[-4., -4.],
       [-4., -4.]])

In [53]:
np.subtract(X,Y)

array([[-4., -4.],
       [-4., -4.]])

In [54]:
np.add(X,Y)

array([[ 6.,  8.],
       [10., 12.]])

In [55]:
np.multiply(X,Y)

array([[ 5., 12.],
       [21., 32.]])

In [56]:
np.divide(X,Y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [57]:
np.sqrt(X,Y)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [58]:
X/Y

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [59]:
X=np.array([[1,2],[3,4]],dtype=np.float64)
Y=np.array([[5,6],[7,8],[9,10]],dtype=np.float64)

In [60]:
X.shape

(2, 2)

In [61]:
Y.shape

(3, 2)

In [62]:
np.add(X,Y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [ ]:
X

In [ ]:
np.exp(X)

In [ ]:
np.log(X)

In [ ]:
np.cos(X)

In [ ]:
np.tan(X)

In [ ]:
#Floor,ceil,Round
X=np.array([[1.5,2.5],[3.1,4.9]],dtype=np.float64)

In [ ]:
X

In [ ]:
np.floor(X)

In [ ]:
np.floor( X)

In [ ]:
np.ceil(X)

In [ ]:
np.round(X)

In [ ]:
X=np.array([[1,2],[3,4]],dtype=np.float64)
Y=np.array([[5,6],[7,8]],dtype=np.float64)
Z=np.array([[9,10],[11,12]],dtype=np.float64)

In [ ]:
X*Y*Z

In [ ]:
np.multiply(X,Y,Z)

In [ ]:
import numpy as np
X=np.array([[1,2],[3,4],[5,6]])
Y=np.array([[5,6],[7,8]])
V=np.array([9,10])
w=np.array([11,12])

In [ ]:
v.dot(w)

In [ ]:
np.dot(v,w)

In [ ]:
X


In [ ]:
X.shape

In [ ]:
np.sum(X)

In [ ]:
np.sum(X,axis=0)

In [ ]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
x

In [ ]:
np.sum(X,axis=0)

In [ ]:
x

In [ ]:
x.T

In [ ]:
np.sum(X,axis=1)

In [ ]:
#Numpy Array copy vs view
arr=np.array([1,2,3,4,5])
X=arr

In [ ]:
print(arr)

In [ ]:
print(X)

In [ ]:
arr[0]=100

In [ ]:
print(arr)

In [ ]:
print(X)

In [ ]:
X[1]=200

In [ ]:
print(X)

In [ ]:
#Numpy Array copy
arr=np.array([1,2,3,4,5])
x=arr.copy()

In [ ]:
print(arr)

In [ ]:
print(X)

In [ ]:
arr[0]=100

In [ ]:
print(arr)

In [ ]:
print(X)

In [ ]:
X[1]=100

In [ ]:
print(X)

In [ ]:
print(arr)

In [ ]:
#Numpy Array copy
arr=np.array([1,2,3,4,5])
x=arr.copy()

In [ ]:
print(arr)

In [ ]:
print(x)

In [ ]:
print(arr)

In [ ]:
arr[0]=100

In [ ]:
print(arr)

In [ ]:
print(x)

In [ ]:
x[1]=100

In [ ]:
print(x)

In [ ]:
print(arr)

In [ ]:
#Numpy Array reshaping
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])


In [ ]:
np.arange(13)

In [ ]:
np.arange(5,13)

In [ ]:
#Numpy Array Reshaping
arr=np.arange(1,13)
arr.shape

In [ ]:
arr.reshape(4,3)

In [ ]:
arr.reshape(3,4)

In [ ]:
arr.reshape(4,3)

In [ ]:
arr_new=arr.reshape(4,3)

In [ ]:
#Flattening the arrays
#2D==>1D
arr_new.reshape(-1)

In [64]:
#Iterating Arrays
np.arange(1,7).reshape(3,2).sum(axis=0)

array([ 9, 12])

In [66]:
#Iterating Arrays
arr=np.arange(1,7).reshape(3,2)

In [67]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
for x in arr:
    print(x)

[1 2]
[3 4]
[5 6]


In [69]:
#Joining Numpy Arrays#10
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [70]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [72]:
#Join two 2D arrays along rows(axis=1)
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
arr1

array([[1, 2],
       [3, 4]])

In [74]:
arr2

array([[5, 6],
       [7, 8]])